export const ACTIVITY_LABELS = {
  CON1: 'Aquaculture trestles or fixed walkways',
  CON2: 'Piled or fixed aquaculture structures',
  CON3: 'Hard coastal defence structures such as rock armour or concrete units',
  CON4: 'Tidal flood defence structures (e.g., flood barriers, tidal gates, sluices)',
  CON5: 'Breakwater, mole or harbour protection structure',
  CON6: 'Bridge or bridge supports in tidal waters',
  CON7: 'Causeway, embankment or coastal access ramp',
  CON8: 'Groyne',
  CON9: 'Jetty, pier or quay',
  CON10: 'Revetment (sloped coastal protection)',
  CON11: 'Sea wall or coastal wall',
  CON12: 'Slipway or boat ramp',
  CON13: 'Floating breakwaters or wave attenuators',
  CON14: 'Pontoons or floating walkways',
  CON15: 'Fixed offshore wind foundations',
  CON16: 'Tidal energy devices or foundations',
  CON17: 'Wave energy device foundations',
  CON18: 'Culverts or constructed tidal channels',
  CON19: 'Intakes',
  CON20: 'Outfalls or diffusers',
  CON21: 'Pipelines or ducts',
  CON22: 'Subsea cables requiring protective construction',
  CON23: 'Artificial reefs or habitat structures',
  CON24: 'Foundations for offshore platforms or similar structures',
  CON25: 'Piles or piled structures',
  CON_OTHER: 'Other structures not listed above',
  DEP1: 'Alternative use of dredged material – beach management',
  DEP2: 'Alternative use of dredged material – habitat creation',
  DEP3: 'Alternative use of dredged material – land reclamation or construction fill',
  DEP4: 'Disposal of dredged material to sea',
  DEP5: 'Disposal of fish waste',
  DEP6: 'Disposal of shellfish waste',
  DEP7: 'Aids to navigation',
  DEP8: 'Anchoring systems',
  DEP9: 'Markers posts',
  DEP10: 'Moorings',
  DEP11: 'Pontoons',
  DEP12: 'Protective mattresses or rock bags',
  DEP13: 'Scientific instruments',
  DEP14: 'Temporary works equipment',
  DEP15: 'Habitat pods, artificial habitat units or reef cubes',
  DEP16:
    'Marine restoration materials (e.g. oyster shells, cobbles, gravel for habitat creation)',
  DEP17: 'Seeding materials (e.g. shellfish seed for habitat enhancement)',
  DEP18: 'Burial at sea',
  DEP19: 'Explosive substances or articles',
  DEP20: 'Fireworks',
  DEP21: 'Use of tracers or dyes',
  DEP_OTHER: 'Other substances or objects not listed above',
  REM1: 'Abandoned fishing equipment',
  REM2: 'Marine litter and debris',
  REM3: 'Rocks, boulders or obstructions',
  REM4: 'Artificial reefs or habitat structures',
  REM5: 'Breakwater, mole or harbour protection structure',
  REM6: 'Bridge or bridge supports in tidal waters',
  REM7: 'Causeway, embankment or coastal access ramp',
  REM8: 'Fixed offshore wind foundations',
  REM9: 'Floating breakwaters or wave attenuators',
  REM10: 'Foundations for offshore platforms or similar structures',
  REM11: 'Jetty, pier or quay',
  REM12: 'Piles or piled structures',
  REM13: 'Pontoons or floating walkways',
  REM14: 'Revetment (sloped coastal protection)',
  REM15: 'Sea wall or coastal wall',
  REM16: 'Slipway or boat ramp',
  REM17: 'Aquaculture equipment (trestles, cages, poles etc.)',
  REM18: 'Culverts or constructed tidal channels',
  REM19: 'Foundation components (e.g. anchors, small footings)',
  REM20:
    'Hard coastal defence structures such as rock armour or concrete units',
  REM21: 'Intakes',
  REM22: 'Outfalls or diffusers',
  REM23: 'Pipelines or ducts',
  REM24: 'Subsea cables requiring protective construction',
  REM25: 'Tidal energy devices or foundations',
  REM26:
    'Tidal flood defence structures (e.g. flood barriers, tidal gates, sluices)',
  REM27: 'Wave energy device foundations',
  REM28: 'Aids to navigation',
  REM29: 'Habitat pods or artificial reef units',
  REM30: 'Moorings',
  REM31: 'Pontoons or floating structures',
  REM32: 'Scientific instruments',
  REM33: 'Survey markers or temporary works equipment',
  REM34: 'Wrecks or items or archaeological remains',
  REM35: 'Sediment samples',
  REM_OTHER: 'Other substances or objects not listed above'
}
